### ISSUE TITLE
Be able to add multiple compositeKeyboardVector steps

### ISSUE THREAD

**Issue by krispya** [hmans/controlfreak#3]
Right now if you add two compositeKeyboardVector steps to a Control then only the last one takes effect. The use case for having more than one would for example have wasd and arrow keys control player movement.

**Comment by hmans** [comment]
That's a very good point - thanks for submitting this issue!

**Comment by hmans** [comment]
With the change in #15, you can supply multiple key bindings as an array to steps that support them, eg:

```ts
controller
  .addControl("move", VectorControl)
  .addStep(
    compositeKeyboardVector(
      ["KeyW", "ArrowUp"],
      ["KeyS", "ArrowDown"],
      ["KeyA", "ArrowLeft"],
      ["KeyD", "ArrowRight"]
    )
  )
```

or

```
controller
  .addControl("fire", BooleanControl)
  .addStep(whenKeyPressed(["Space", "Enter"]))
```

This allows you to configure multiple keys (any number of them), but keeps things easy to reason about (because no keys pressed still equates to a zero vector, so having multiple of these passes would have quickly become kinda messy.)
